### ISSUE TITLE
Mod_rewrite not enabled

### ISSUE THREAD

**Issue by awbradshaw** [samthomson/flot#8]
Trying to install on a shared server with the default .htaccess. Won't install with error: mod_rewrite not enabled. But it is according to hostgator. Any idea what the issue may be? Thanks.

**Comment by samthomson** [comment]
Shall check this out later this evening, sounds like the code that checks for mod_rewrite is wrong.
It would be very helpful if you could share more details on your hosting set up (as is safe to do so).

Thanks for reporting, Sam.

**Comment by samthomson** [comment]
Either flot is falsely reporting mod_rewrite as disabled, or your hosting set up is wrong.
I can't fully replicate the issue on your hosting, but guess the problem lies with flot.

PHP provides a nice way to do lots of 'stuff' in a platform agnostic manner. Not everything though. Determining if mod_rewrite is enabled across all platforms requires a bit more coding than flot has, at this stage.

I have added a bit more to the checking mechanism, but it is likely it will still falsely-report. This is until I can replicate the issue, or spend some more time coding this feature, which at the moment seems too minor.

If you pull down the latest version, you'll see the start screen now has a 'force flot start' button, for if you feel confident the requirements are indeed satisfied.
Once set up if you go to the settings tab, and then the flot settings. You'll see there is now near the bottom an indicator on whether flot thinks mod_rewrite is enabled or not.

**Comment by awbradshaw** [comment]
Thanks Sam. It worked this time, no problem.

The only issue now is that when I edit a page (using default theme), and save I get a "individual item not defined" notice. I go back to the edit screen and can see no content in the wysiwyg field, but the content has been updated.

Same thing with adding pages. They add OK, but I cannot go back and edit the content as it doesn't show in the editing area.

Aaron

**Comment by samthomson** [comment]
Aaron, thanks for reporting, and your patience!

There was quite a bug there, fixed now.
Edits to a webpage (any type) would update the corresponding live website page, but would not permeate within flot, causing subsequent edits to be done from scratch (blank edit screen, without your last changes).
This was due to a big re-factoring of code when making the 'preview' feature about ten days ago.

Thanks, Sam

**Comment by samthomson** [comment]
You can pull down the latest version, or update flot directly from the settings > flot page.
